### ISSUE TITLE
How to manage installation of BepInExPack?

### ISSUE THREAD

**Issue by Nipplechips** [wahlfeld/valheim-on-aws#28]
I have used this project to set up a server that a community is now using to play.  They are now requesting some mods be available.  It seems a dependency of these mods is [BepInExPack](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/).

### Firstly, a question regarding installing this:

(from BepInEx installation instructions)
> 1. Extract the archive into a folder. **Do not extract into the game folder**.
> 2. Move the contents of BepInExPack_Valheim folder into <Steam Location>\steamapps\common\Valheim.

For point 1, in the context of this project, what is "the game folder"? I would assume its the path which is given to `+force_install_dir` argument within the `install_valheim.sh` script?

For point 2, from what I can tell, the EC2 instance doesn't ever have Steam installed on it and therefore `<Steam Location>` as detailed in the BepInEx installation guide does not exist?  If I am correct, where would we unpack BepInEx to?

---

### Secondly, a question regarding the configuration of BepInEx in this environment:

(from BepInEx  **game configuration** instructions)

> 2. In Steam, go to game's properties and set game's launch arguments to `./start_game_bepinex.sh %command%`
> Note to advanced users: You can change ./start_game_bepinex.sh to full path to the script. This way you can install this pack entirely outside of game folder.

I dont really understand what is happening inside of `start_game_bepinex.sh` but this looks like we need this script to be executed just before the game server is launched.  Again, we dont have Steam installed on this instance and so to "go to game's properties and set game's launch arguments" seems impossible.  Wondering if I even need to do this in the context of a game **server** instead of client-side game executable?

(from BepInEx  **server configuration** instructions)

> 3. Run start_server_bepinex.sh to start the server.

Easy enough in principle.  But we already have a `start_valheim.sh` which is used to start the game server as well as manage cname and backups.  The `start_server_bepinex.sh` script just appears to set some env variables it needs to run before running the `./valheim_server.x86_64` application so can I just append these export statements to what we already have in `start_valheim.sh` ?  The reason I ask is because both scripts seem to use the `LD_LIBRARY_PATH` variable and I have no idea on the implications of mucking around with this.

I appreciate that none of this is directly related to this project so i appreciate any time and thoughts you have to spare on this outside issue.

**Comment by wahlfeld** [comment]
Server-side mods aren't something I'm familiar with so without looking into it I can't be of much help. I do use _client-side_ mods myself, and to my surprise they work quite well. In fact, I've not come across a mod that hasn't worked for me yet. I think this is the only game I'm aware of where client-side mods natively work in a multiplayer setting. Anyway, let me know how you go (PRs welcome).

**Comment by gertminov** [comment]
I got the server running with ValheimPlus, wich also installs BepInEx so this could be helpfull. Disclaimer: I have zero knowledge about aws or terraform or linux bash scripting so this is omega janky.

## Downlad and install the mod into the server
1. add `unzip` to the installed packages in `/module/local/userdata.sh` (from line 6 on there is a long `apt install ...`command, just append it there
2. edit the `/module/local/install_valheim.sh` to download and install ValheimPlus. append these two lines to the end of the script
```bash
curl -LJ0 https://github.com/Grantapher/ValheimPlus/releases/download/0.9.12.0/UnixServer.zip -o /home/vhserver/valheim/ValheimPlus.zip # download the zip file from github and save it to the server
unzip -o /home/${username}/valheim/ValheimPlus.zip -d /home/${username}/valheim/ #unpack the zip file to the local machine
```
## Edit the start file to run the Mod and read the config file from S3
3. edit the `/module/local/start_valheim.sh` to include the start parameters from the `start_server_bepinex.sh`. put these lines above the `export templdpath=$LD_LIBRARY_PATH`
```bash
# BepInEx-specific settings
# NOTE: Do not edit unless you know what you are doing!
####
export DOORSTOP_ENABLE=TRUE
export DOORSTOP_INVOKE_DLL_PATH=./BepInEx/core/BepInEx.Preloader.dll
export DOORSTOP_CORLIB_OVERRIDE_PATH=./unstripped_corlib

export LD_LIBRARY_PATH="./doorstop_libs:$LD_LIBRARY_PATH"
export LD_PRELOAD="libdoorstop_x64.so:$LD_PRELOAD"
####

```
4. edit the `start_valheim.sh` to fetch the `valheim_plus.cfg` from S3 on server start
```bash
VHPLUS_CONFIG=$(aws s3api head-object --bucket ${bucket} --key "valheim_plus.cfg" || true >/dev/null 2>&1)
if [ -z "$${VHPLUS_CONFIG}" ]; then
	echo "No ValheimPlus config (valheim_plus.cfg) found on S3"
else
	echo "found ValheimPlus config on S3"
	aws s3 cp "s3://${bucket}/valheim_plus.cfg" "/home/${username}/valheim/BepInEx/config/valheim_plus.cfg"
fi

```
