### ISSUE TITLE
Add section to readme showing how to enable/add mods and upload existing worlds

### ISSUE THREAD

**Issue by GrayedFox** [wahlfeld/valheim-on-aws#98]
Awesome project, thanks heaps!

I think I can probably figure out how to upload an existing world (the `.db` and `.fwl` files) based on looking into the `backup.sh` and other shell scripts but, if possible, could you add some sections to the readme that:

1. show how to add/enable mods on the server (I can't live without craft-from-containers!), and
2. show where the right location is to upload an existing `.db` and `.fwl` file?

I used `aws cp local.fwl valheim$uniqueIdNumber` after spinning up the server for the first time, but that didn't seem to work - probably because the server was already running and the backup and save scripts wouldn't have seen those files when the instance spun up.

Keep up the great work! Tag me for a code review any time - if I do figure out how to do the above I will make a PR adding those sections to the readme myself ⚡

**Comment by wahlfeld** [comment]
I use mods client-side and they generally all seem to work on the server. I'm not aware of how to host mods server-side because I've never needed to.

The world files are expected to be in "/home/${username}/.config/unity3d/IronGate/Valheim/worlds_local/".

**Comment by GrayedFox** [comment]
I just checked and both mods I'm using are working without issue - assumed it would be something the server needed either using an ACL or through some setting - but it just works so that's all gravy.

Will close this now as it's resolved, your comment shows where to put the world and db files if wanting to use an existing world, thanks again
